/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_pronaya_ndkdemo_nativeInterface */

#ifndef _Included_net_pronaya_ndkdemo_nativeInterface
#define _Included_net_pronaya_ndkdemo_nativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_pronaya_ndkdemo_nativeInterface
 * Method:    register_image_front
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_net_pronaya_ndkdemo_nativeInterface_register_1image_1front
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     net_pronaya_ndkdemo_nativeInterface
 * Method:    register_image_back
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_net_pronaya_ndkdemo_nativeInterface_register_1image_1back
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     net_pronaya_ndkdemo_nativeInterface
 * Method:    prediction_f1
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_net_pronaya_ndkdemo_nativeInterface_prediction_1f1
  (JNIEnv *, jobject, jlong, jlong, jlong, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     net_pronaya_ndkdemo_nativeInterface
 * Method:    prediction_f2
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_net_pronaya_ndkdemo_nativeInterface_prediction_1f2
  (JNIEnv *, jobject, jlong, jlong, jlong, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     net_pronaya_ndkdemo_nativeInterface
 * Method:    prediction_f3
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_net_pronaya_ndkdemo_nativeInterface_prediction_1f3
  (JNIEnv *, jobject, jlong, jlong, jlong, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     net_pronaya_ndkdemo_nativeInterface
 * Method:    prediction_f4
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_net_pronaya_ndkdemo_nativeInterface_prediction_1f4
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jint, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
